# THIS ZSHRC FILE IS NOT READY!

## User Configurations

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


### Environment variables

# Include non-root Homebrew for linux path
if [ -d $HOME/.linuxbrew ]
then
    export PATH=$HOME/.linuxbrew/bin:$PATH
fi

export VISUAL=vim
export EDITOR=vim

# GPG
export GPG_TTY=$(tty)
if [ -f "${HOME}/.gpg-agent-info" ]; then
    . "${HOME}/.gpg-agent-info"
    export GPG_AGENT_INFO
    export SSH_AUTH_SOCK
fi
# Start the gpg-agent if not already running
if ! pgrep -x -u "${USER}" gpg-agent >/dev/null 2>&1; then
    gpg-connect-agent /bye >/dev/null 2>&1
fi

# Homebrew
HOMEBREW_MAKE_JOBS=4

